name: KataRuntime UI CI

on:
  push:
    tags: [ '20[0-9]+.[0-9]+.[0-9]' ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a Release T/F'
      kata_ui_version_letter:
        description: 'Additional Letter to add to the version'
        
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      
    - name: Set Pre-Build ENV Variables
      if: github.event.inputs.kata_ui_version_letter
      run: |
          echo "UI_VERSION_LETTER=${{github.event.inputs.kata_ui_version_letter}}" >> $GITHUB_ENV
      
    - name: Build the in Docker
      run: |
        chmod +x ./build_in_docker.sh
        chmod +x ./source/kata.runtime.ui/pkg_build.sh
        ./build_in_docker.sh -u
   
    - name: Set Post-Build ENV Variables
      id: version
      run: |
          echo "UI_VERSION=${{env.DATE}}${{env.UI_VERSION_LETTER}}" >> $GITHUB_ENV
   
    - name: Upload Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: kata.runtime.ui-${{env.UI_VERSION}}-x86_64.txz
        path: ./archive/kata.runtime.ui-*

    - name: Set Release ENV Variables On Manual
      if: github.event_name == 'workflow_dispatch'
      run: |
          echo "DO_RELEASE=${{github.event.inputs.create_release}}" >> $GITHUB_ENV
          echo "RELEASE_TAG_NAME=${{env.UI_VERSION}}" >> $GITHUB_ENV
          
    - name: Set Release ENV Variables On Auto
      if: github.event_name != 'workflow_dispatch'
      run: |
          echo "DO_RELEASE=T" >> $GITHUB_ENV
          echo "RELEASE_TAG_NAME=${{github.GITHUB_REF}}" >> $GITHUB_ENV
          
    - name: Create Manual Release
      id: create_release
      uses: actions/create-release@v1
      if: env.DO_RELEASE == 'T'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:  ${{env.RELEASE_TAG_NAME}}
        release_name: UI Package ${{env.RELEASE_TAG_NAME}}
        draft: true
        prerelease: false
    
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      if: env.DO_RELEASE == 'T'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./archive/kata.runtime-${{env.UI_VERSION}}-x86_64.txz
          asset_name: kata.runtime-${{env.UI_VERSION}}-x86_64.txz
          asset_content_type: application/octet-stream
